# Generated by Django 4.1.5 on 2023-02-10 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truckclass',
            name='truck',
        ),
        migrations.DeleteModel(
            name='Rule',
        ),
        migrations.DeleteModel(
            name='Ruleset',
        ),
        migrations.DeleteModel(
            name='Truck',
        ),
        migrations.DeleteModel(
            name='TruckClass',
        ),
    ]
