# Generated by Django 4.1.5 on 2023-02-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_competition_gates_per_round_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='no_of_rounds',
            field=models.IntegerField(),
        ),
    ]
