# Generated by Django 4.1.5 on 2023-02-28 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_alter_competition_no_of_rounds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='no_of_rounds',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Please enter a number greater than or equal to 1'), django.core.validators.MaxValueValidator(30, message='Please enter a number less than or equal to 30')]),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'The email you entered already exists.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='user_name',
            field=models.CharField(error_messages={'unique': 'The username you entered already exists.'}, max_length=150, unique=True),
        ),
    ]
