# Generated by Django 4.1.5 on 2023-03-03 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_alter_competition_no_of_rounds_alter_newuser_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='score',
            new_name='comp',
        ),
    ]
