# Generated by Django 4.1.5 on 2023-02-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_alter_competition_no_of_rounds_alter_newuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='user_name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
