# Generated by Django 4.1.5 on 2023-03-11 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_alter_newuser_email_alter_newuser_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruleset',
            name='rule',
        ),
        migrations.AddField(
            model_name='rule',
            name='ruleset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database.ruleset'),
            preserve_default=False,
        ),
    ]
