# Generated by Django 4.1.5 on 2023-03-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_alter_score_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='time_taken',
            field=models.CharField(max_length=20),
        ),
    ]
