# Generated by Django 4.1.5 on 2023-03-10 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_alter_score_time_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='ruleset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database.ruleset'),
            preserve_default=False,
        ),
    ]
