# Generated by Django 4.1.5 on 2023-03-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_remove_ruleset_rule_rule_ruleset'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='ref_code',
            field=models.CharField(blank=True, default='U9HAS', editable=False, max_length=10, unique=True),
        ),
    ]
