# Generated by Django 4.1.5 on 2023-03-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_competition_ref_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='ref_code',
            field=models.CharField(blank=True, default='8T6HM97N0Y', editable=False, max_length=10, unique=True),
        ),
    ]
