# Generated by Django 4.1.5 on 2023-03-10 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_remove_rule_ruleset_ruleset_rule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruleset',
            name='rule',
        ),
        migrations.AddField(
            model_name='competition',
            name='ruleset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database.ruleset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rule',
            name='ruleset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database.ruleset'),
            preserve_default=False,
        ),
    ]
