# Generated by Django 4.1.5 on 2023-03-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_remove_ruleset_rule_competition_ruleset_rule_ruleset'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='ref_code',
            field=models.CharField(blank=True, default='I30N7', editable=False, max_length=10, unique=True),
        ),
    ]
