# Generated by Django 4.1.5 on 2023-03-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_alter_competition_ref_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='ref_code',
            field=models.CharField(blank=True, default='QWS0R', editable=False, max_length=10, unique=True),
        ),
    ]
