# Generated by Django 4.1.7 on 2023-03-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_alter_competition_ref_code_alter_rule_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='ref_code',
            field=models.CharField(blank=True, default='NNP0N', editable=False, max_length=10, unique=True),
        ),
    ]
